[src]
# Explicitly exclude these directories (takes precedence over include)
exclude = [
    ".venv",
    "tests",
    "archive",
]

[rules]
invalid-argument-type = "ignore"
unsupported-operator = "ignore"
invalid-parameter-default = "ignore"
invalid-type-form = "ignore"
invalid-return-type = "ignore"
unresolved-attribute = "ignore"
possibly-missing-attribute = "ignore"